### ISSUE TITLE
How do you build the module ?

### ISSUE THREAD

**Issue by catull** [TwanoO67/ngx-admin-lte#13]
I have cloned the repo.

package.json contains 4 scripts:

- `transpile`
- `package`
- `minify`
- `build`, which invokes the previous 3

`transpile` does not succeed.
`package` neither, it invokes `rollup`, which is missing a rollup.config.js.
`minify` is not even taking off.

So, how do you build the npm module ?

I got `transpile` - more precisely `tsc` - to build, but it barfs up on "compiling" node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts(2,22), despite the fact that I explicitly exclude "node_modules/" from transpilation.

See PR https://github.com/TwanoO67/ngx-admin-lte/pull/12.

**Comment by TwanoO67** [comment]
Hello,

I honestly don't know how to build that separately (and neither if it has a purpose).

This installation as a dependency is quite new for me, and for the moment I never add to "compiling it separately" to make it work, as it should be compiled by the angular-cli project that include this package (so as a part of the node_modules, of the parent project)

But I suppose that there's a way to compile that, in order to serv it through npm as a "dist" package. 
But i didn't found the way to do that, so If you know how, I'm interrested :)

For the moment, I personnaly use the project: 
https://github.com/TwanoO67/bootstraping-ngx-admin-lte
And do my modification directly in the node_modules folder to test it in real contexte, before submitting the change to this project and npm.

**Comment by catull** [comment]
I use this npm module, which means I have to make sure the module builds cleanly and can be published to npm registry.

Like I said, right now I have no clue how you publish it to npm registry.

Each build on Travis has failed, which is not reassuring.

**Comment by TwanoO67** [comment]
There's no travis.yml on this project... that's why it fail.

You don't have to publish yourself on npm. 
It's already done by myself, so I don't know what you're trying to achieve here...

**Comment by catull** [comment]
There is no correspondence between the code in this repository and the npm module that is published, there is no automated way.

I do NOT say you have ill intentions, still, the process of publishing is mysterious.

What I am missing right now is to be able to switch off a lot of features.
Take for instance the "social media" aspect of AdminLTE, the "Likes", the "Followers", the "Avatars" etc.  I do not need any of those.

There is an issue (#11) addressing some of that, but the issue is still open.

**Comment by TwanoO67** [comment]
Or course the npm code is the same...
Version in npm are related to this repository tags.
Develop is the current work in process.
Once à new feature has been finished, I merge it to master, flag thé version number on a tag, and publish it on npm

**Comment by TwanoO67** [comment]
And for the "disabling" part.
I am currently working on that, and some of those thing will be in the 0.6.0 release.
But i thats not fast enough for you I would ne happy To have some help...

**Comment by TwanoO67** [comment]
@catull version 0.6.2 is out, and it provide some more configuration options (take a look at the "Configuration" part of the readme).

Please open another issue if you need some more personnalisation options
